project:
  type: book
  output-dir: _book

book:
  title: "Entre o Pós-Abolição e a História Digital"
  subtitle: "usos e sentidos do termo pós-abolição nos Simpósios Nacionais de História da ANPUH (2013 - 2019)"
  author: "Priscila Valverde Silveira"
  date: "20/06/2022"
  comments:
    hypothesis: true
  chapters:
    - index.qmd
    - agradecimento.qmd
    - resumo.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - conclusao.qmd
    - references.qmd
  sharing: 
    - twitter
    - facebook
  downloads: 
    - pdf
    - epub
    - docx
  repo-url: https://github.com/priscilavalverdes/TCC-Pos-abolicao
  repo-actions: [edit, issue, source]
  page-footer:
    center: 
      - text: "Copyright 2022, Priscila Valverde Silveira"
        href: "https://github.com/priscilavalverdes/TCC-Pos-abolicao"

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    lang: pt
    author-meta: Priscila Valverde Silveira
    date-meta: 29/06/2022
  pdf:
    documentclass: scrreprt
    colorlinks: true
    toc-title: Índice
    indent: true  
    lang: pt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    documentclass: book
    epub-cover-image: cover.png
  docx:
    toc: true
    toc-title: Índice
    number-sections: true
    highlight-style: github
    reference-doc: custom-reference-doc.docx
    lang: pt