# Agradecimentos {.unnumbered}

Agradeço ao Tempo, que se encarrega de colocar tudo em seu devido lugar: pessoas, caminhos e sentimentos. Agradeço a minha mãe, Eliete Valverde, meu amor, que me ensinou a resistir e por quem me reinvento todos os dias. 

Agradeço a Eric Brasil, meu orientador - a quem posso chamar de amigo -, por todo incentivo e por ter me ensinado o significado do pronome “nós” dentro da universidade. Sem ele, esta monografia não teria sentido. 

Agradeço aos professores Leonardo Nascimento e Paulo Fonseca, do Laboratório de Humanidades Digitais da UFBA- LABHD, do qual me sinto feliz em fazer parte, pelo acolhimento e parte da formação técnica. Sem o laboratório não teria sido possível desenvolver a pesquisa da maneira que se encontra. 

Agradeço a Ana Carolina Veloso, minha amiga, pela parceria e por junto com Eric ter me ensinado a trabalhar em equipe. 

Agradeço às professoras Maria Cláudia Cardoso Ferreira e Anita Lucchesi pelo aceite em compor a banca e pela leitura e contribuição para esta monografia. 

Agradeço à Unilab, especialmente ao Programa Institucional de Bolsas de Iniciação Científica, que possibilitou o desenvolvimento da pesquisa através de concessão de bolsa para o projeto "Pós-Abolição: sentidos usos e produção acadêmica (2004-2019)". 

Obrigada por terem construído junto comigo este trabalho!
