# O que é o Pós-abolição? Situando o debate historiográfico.

Segundo o Manifesto de Fundação do GT Nacional Emancipações e Pós-Abolição da ANPUH, do ano 2013, o pós-abolição no Brasil se consolidou enquanto um campo historiográfico autônomo, embora esteja ligado a história da escravidão. Devido a importância do crescimento do campo, ocorreu a criação do referido GT, que elenca diversas temáticas como parte deste campo, e reforça a necessidade de estudar o pós-abolição a partir de um conjunto de elementos particulares (“Manifesto de Fundação”, 2014).[^1]

[^1]: Acessado em 21/10/2021. Disponível em:https://emancipacoeseposabolicao.wordpress.com/manifesto-de-fundacao/

Esse conjunto de elementos apontados no Manifesto de Fundação, partem da concepção de que para estudar o pós-abolição e entender seu processo histórico é necessário “invadir outras veredas da história do Brasil republicano, envolvendo espaços, tempos e agências variadas”(GOMES; DOMINGUES, 2011).

O pós-abolição no Brasil possui como marco cronológico o desmonte total do regime escravista enquanto sistema jurídico, através da Lei 3.353, promulgada no dia 13 de maio de 1888. No entanto, a maior parte da população negra no Brasil - último país independente das Américas a abolir a escravidão - na data da abolição, já era livre, o que se relaciona a uma taxa importante de alforrias entre os séculos XVII e XVIII, à intensificação das ações abolicionistas por todo século XIX e, sobretudo, pela constante mobilização de escravizados pela conquista de sua liberdade (CHALHOUB, 2011). O fim do regime escravista marca o início de um novo período na sociedade Brasileira, seguido pela instauração do Regime Republicano em 1889, com o fim do direito à propriedade sobre os corpos negros. Para a população egressa do cativeiro e seus descendentes, esta nova configuração político-social deveria garantir direitos que, durante o regime escravista, dependiam exclusivamente do poder senhorial, e, principalmente, deveria assegurar juridicamente o direito à liberdade e à cidadania. 

No entanto, a abolição não garantiu a esta população a possibilidade de uma emancipação completa, pois, se durante a escravidão as hierarquias sociais estavam pautadas no pressuposto de raças de forma clara e assegurada, no pós-abolição as estruturas raciais foram reconfiguradas, continuando intrínsecas, mas sustentadas sob outros elementos (OLIVEIRA, 2017, p. 27). A ausência de políticas públicas que atendessem a problemas específicos da população negra no Brasil, e que buscassem diminuir as desigualdades foram negligenciadas e mesmo convertidas em políticas que só reforçaram as práticas racistas e que afundavam ainda mais esta população em um abismo de desigualdades (BRASIL, 2016, p. 73). 

Na historiografia brasileira, o termo pós-abolição começa a ganhar destaque na década de 1990, mas tem sua consolidação nos anos 2000, principalmente após a publicação em 2004 do artigo “O pós-abolição como problema histórico: balanços e perspectivas” de Ana Lugão Rios e Hebe Matos. Nesse artigo, as autoras apontam a centralidade das ações provenientes da população egressa do cativeiro como fator para compreender os sentidos e estratégias destas populações após a abolição. A interpretação histórica baseada numa perspectiva de fronteiras agrárias abertas/fechadas ou ainda do silêncio sobre a cor nas análises sobre as primeiras décadas do regime republicano induziu a um desaparecimento da população negra da historiografia. A partir do diálogo com trabalhos sobre o Caribe e os EUA, com os trabalhos da história social da escravidão e da história oral, memória, história social da cultura e ainda os debates sobre raça e racismo na sociedade brasileira, as autoras apontam uma nova perspectiva historiográfica, que possibilita a população negra emergir no processo histórico sob diversos caminhos que desabilitam os conceitos racistas pautados biologicamente sob os pressupostos de inferioridade (RIOS e MATTOS, 2004).

As autoras apontam a necessidade da historiografia encarar esse período como um campo de estudo específico, independente do campo da história da escravidão. Obviamente, o princípio básico para a compreensão do pós-abolição é sua própria ligação com o fim da escravidão. Entretanto, essa distinção é importante, segundo as autoras, para que possamos analisar as diferentes formas, atualizações, transformações e permanências das relações raciais e sociais no Brasil nos últimos 130 anos após o fim do regime escravista.

Como o termo pós-abolição no Brasil tem uma conotação especificamente ligada ao 13 de maio de 1888 e ao fim completo do sistema escravista, ele traz consigo o sentido de marco temporal. Entretanto, também possui uma dimensão de marco teórico, por possibilitar a análise de experiências sociais de pessoas negras livres numa sociedade sem escravidão, mas que mantém e recria formas de hierarquização racial e social. 

Para Petrônio Domingues e Flávio Gomes, o pós-abolição no Brasil:

> Foi um período de longa duração, abrangendo desde a propaganda abolicionista (e operária, vertente pouco conhecida), em cidades como o Rio de Janeiro, Santos, São Paulo, Porto Alegre e Salvador dos anos 1880 até os movimentos sociais de luta antirracista na época da redemocratização, cerca de um centúria depois. Histórias diversas envolvendo biografias e instituições... Acompanhar seu processo histórico também significa - e isso precisa ser enfatizado – invadir outras veredas da história do Brasil republicano, envolvendo espaços, temos e agências variadas. (GOMES e DOMINGUES, 2011, p. 9-10)

Fernanda Oliveira, em sua tese de doutorado, aponta o campo de estudo do pós-abolição como um diálogo entre os estudos da escravidão e a herança desta para o período subsequente, afirmando que:

> O campo de estudos do pós-abolição é entendido não como dissociado dos estudos da escravidão, tampouco como legado daquele período, o que diferencia é o foco do olhar nos diálogos abertos com a abolição. É estritamente nesse sentido que adoto o pós-abolição: como campo de estudos que oferece um repertório de análises,cujo problema histórico está centrado nas experiências de liberdade, e especialmente de cidadania, de pessoas escravizadas e seus descendentes após a abolição da escravidão, identificados e hierarquizados nas relações sociais por termos que evocam uma ideia de raça.(OLIVEIRA, 2017, p. 27)

Portanto, o pós-abolição é um termo que possibilita estudar não apenas sujeitos históricos negros, mas sim é uma chave analítica para toda a história do Brasil.

Diante da emergência de eventos, publicações e projetos de pesquisa no Brasil sobre o pós-abolição nos anos 2000, e da grande adesão em Simpósios Temáticos vinculados ao tema nos Simpósios Nacionais de História da ANPUH, um grupo de historiadores e historiadoras se reuniu no XXVII Simpósio Nacional, na cidade de Natal em 2013, e fundou o Grupo de Trabalho Nacional Emancipações e Pós-abolição (Gtep). Desde então, o pós-abolição vem se consolidando como um campo historiográfico autônomo, que aborda variados caminhos teóricos e metodológicos e fornece um vasto campo para a história nacional e para entender conjunturas sociais. 

Dada a crescente importância do termo nas pesquisas e por entendermos o pós-abolição sob uma ótica da historiografia atual enquanto um campo teórico-metodológico vasto, mas que ainda tem muitas possibilidades de crescimento, e diante da importância das publicações decorrentes dos Simpósios Nacionais de História da ANPUH para a produção historiográfica no Brasil, nos propomos a analisar de que maneira o termo tem sido utilizado em tais publicações a partir de 2013, ano de fundação do Gtep.

A ANPUH, inicialmente Associação Nacional dos Professores Universitários de História, foi fundada em 1961 em São Paulo na cidade de Marília em decorrência da realização de um Simpósio que objetivava discutir o currículo de História, os problemas relacionados ao ensino de História nas universidades e a Reforma Universitária, sendo estruturado inicialmente por uma Comissão Executiva, Convidados de Honra, Comissões Especializadas, Cinco Temários, Regulamento do Simpósio, três Conferências e sete Sessões. Nesse momento, seu corpo de associado era apenas de professores universitários, incluindo desde seu início discussões sobre a profissionalização do ensino e sobre a pesquisa na área de História, relacionadas tanto a graduação como a pós-graduação(FALCON, 2011). 

Posteriormente, a ANPUH passou a ter um corpo de associados diversificado, com professores de Ensino Fundamental e Médio, profissionais que atuam em instituições de patrimônio e memória e em arquivos púbicos e privados, o que resultou em 1993 na mudança do nome da organização para Associação Nacional de História, sob o mesmo acrônimo. Atualmente os simpósios acontecem intercalados de dois em dois anos, divididos entre estaduais (quantidade de edições varia conforme o Estado) e nacionais (na 31° edição).  Os Simpósios nacionais da ANPUH são o evento de maior relevância para a historiografia no Brasil e na América Latina, e a instituição exerce influência na consolidação de direitos para a categoria, por exemplo, na aprovação da Lei 14.038/2020 que regulamenta a profissão de historiador. 

Atualmente a ANPUH possui duas revistas para publicação: a Revista Brasileira de História e a revista digital História Hoje e conta com dezenove grupos de trabalho. 

Buscamos nos métodos da História Digital uma forma de analisar as diversas possibilidades de fontes existentes nos meios digitais no intuito de apontar reflexões sobre o uso do termo pós-abolição nas recentes produções acadêmicas da disciplina de História. Para isso, utilizamos uma metodologia híbrida, envolvendo raspagem de dados através de scripts, software para apoio à pesquisa qualitativa e gerenciador bibliográfico associados à leituras e discussões do referencial teórico sobre Humanidades Digitais e o Pós-abolição no Brasil e nas Américas. Detalharemos o desenvolvimento da pesquisa no capítulo a seguir.
