# Entre o pós-abolição e a História Digital.

## Parte I -Reflexões teórico-metodológicas sobre as fontes. 

Segundo Zaagsmabmgn (2013, apud Telles(2017, p. 84)), é nos Estados Unidos, na década de 1960, influenciada pela Nova História Econômica, que se percebe inicialmente o interesse em analisar dados quantitativos com computadores, tendo o ano de 1963 a publicação sobre as obras de São Tomás de Aquino feita por Roberto Busa como marco do início da historiografia digital. Após isso, o campo passou por longo período de ascensão, perdendo espaço na década de 1980 para análises mais voltadas para a narrativa histórica.

No entanto, em 1980 com a popularização do uso dos computadores e em 1990 com a criação da internet, bases de dados foram criadas com a digitalização de fontes históricas e discussões online foram implementadas como prática acadêmica, além do fomento de projetos institucionais na área de comunicação e de preservação de  patrimônio.(TELLES, 2017)

Telles argumenta que inicialmente a História Digital parte das reflexões sobre a digitalização de várias formas de arquivo para o historiador, o uso do computador na prática de pesquisa, além da utilização dos meios digitais como forma de difusão de conhecimentos históricos, o que recai na discussão sobre História Pública (Telles,2017). 

Entretanto, é importante destacar que os debates sobre os caminhos da historiografia digital apontam para uma variedade de filiações teóricas e metodológicas ao longo do século XX. Segundo Crymble, é mais correto buscarmos compreender as múltiplas histórias por trás desse processo, analisando as diferentes práticas e reflexões que precederem o próprio termo história digital (CRYMBLE, 2021). Já em 2014, Anitta Luchesi propôs uma análise comparativa entre a *Digital History* estadunidense e a *Storiografia Digitale* italiana, pensando as diferentes abordagens e objetos de pesquisa, e sobretudo como impactam na epistemologia da história (LUCHESI, 2014).

Essas reflexões são extremamente importantes, e, partindo delas, propomos também refletir sobre as possibilidades de utilizarmos dados que são próprios dos meios digitais como fontes. Mathew Salganik aponta dois padrões de dados como fundamentais para a pesquisa nos meios digitais, os dados *readymades* (prontos) e os *custommades* (personalizados) (SALGANIK, 2018).

Essa diferenciação, embora esteja em sua obra apresentada no âmbito da Ciência Social Computacional, se estende a análise de dados digitais para qualquer disciplina pois, trata de compreender a possibilidade de utilização de fontes criadas em seu fim específico ou fontes que são remodeladas e adequadas passando a serem utilizadas com outra finalidade que não a de sua criação.

Assim, os papers publicados nos Anais da ANPUH, à primeira vista, podem ser identificados como dados *readymades*, por estarmos construindo uma análise a partir da finalidade específica para a qual foram criados: análise da produção historiográfica em determinado recorte temporal. No entanto, esses mesmos dados passaram por uma processo de ressignificação (*repurpose*, nas palavras de Salganik) ao utilizarmos seus metadados não apenas como um dado de identificação mas como um dado analítico que pode indicar tendências específicas sobre a produção historiográfica acerca do pós-abolição, constituindo uma base de dados específica para análise. Ou seja, nos apropriamos de um conjunto de dados, os reorganizamos como dados tabulares, extrapolando sua finalidade original, tornando-os *custommades*. Assim, observando mais detalhadamente nossos papers, os nossos dados representam uma combinação desses dois padrões propostos por Salganik (2018).

Jensen(2020) define os metadados como:

> Metadados são, em sua essência, dados sobre dados, pode ser, o que normalmente foi registrado em uma auxílio de busca(por exemplo, data, criador e local). Mas também pode ser muito mais do que isso, incluindo descrições de assunto muito detalhadas espalhadas por categorias que descrevem qualquer coisa, desde conteúdo a material, necessidade de preservação ou direitos autorais.(Jensen, 2020, p.? tradução nossa)

Os metadados, portanto, "explicam, contextualizam, conferem veracidade ao documento” (Brasil e Nascimento, 2020, p. 202). A análise de alguns metadados já presentes nos papers como instituição, autoria, titulação e, a construção de outros através de identificadores criados nas etiquetas do Atlas.ti como recorte espacial e recorte temporal, nos indicaram alguns aspectos dos perfis de autores e das produções, possibilitando a identificação de tendências de correntes historiográficas no campo, o que será detalhado no capítulo III da monografia. 

Passando da discussão da identificação de fontes em meios digitais para a análise historiográfica da fonte em si, podemos buscar entender inicialmente o uso das fontes digitais sobre três pontos:

Em primeiro lugar, sobre o que pode ser compreendido como um documento utilizado como fonte historiográfica, “o que entendemos efetivamente por documentos senão um ‘vestígio’, quer dizer, a marca, perceptível aos sentidos, deixada por um fenômeno em si mesmo impossível de capitar?” (BLOCH, 2002). Assim, podemos entender que as fontes podem ser qualquer vestígio decorrente de alguma ação humana no tempo. Refletindo sobre a possibilidade da pesquisa historiográfica em meios digitais, existe uma variedade de fontes possíveis que ainda são recentes para nossa disciplina: as redes sociais, imagens publicadas em sites, etc. Mas queremos propor aqui especificamente pensar os ‘vestígios’ deixados pela produção das publicações acadêmicas em meios digitais - que em certa medida podem ser compreendidas como fontes diretas pois foram construídas com finalidade historiográfica. Em nossa pesquisa, escolhemos especificamente tratar dos papers dos Simpósios Nacionais de História da ANPUH. Escolhemos estas publicações diante da análise estar completamente voltada ao termo pós-abolição, e como já mencionado, houve a criação do GT Emancipações e Pós abolição em 2013, além dos Simpósios serem o maior evento de História do país.

Em segundo lugar, salientando a importância do caráter subjetivo do ofício do historiador de entender além do que intencionalmente foi dito, buscamos analisar não apenas o corpo das publicações em si, mas o que o conjunto da escrita associada a seus metadados (informações sobre as publicações) podem nos possibilitar questionar, pois:
	
> Do mesmo modo, até nos testemunhos mais resolutamente voluntários, o que os textos nos dizem expressamente deixou hoje em dia de ser o objeto predileto de nossa atenção. Apegamo-nos geralmente com muito mais ardor ao que ele nos deixa entender, sem haver pretendido dizê-lo. (BLOCH, 2002, p.78)

E em terceiro lugar, entendendo a importância da construção de boas perguntas sobre o objeto de pesquisa, diante do caminhar da sociedade contemporânea, da qual a tecnologia digital é indissociável, hoje encontramos nesses meios os ‘vestígios’ de uma sociedade informatizada, fazendo-se imprescindível que nos adequemos a esses novos meios se quisermos acompanhar os registros dessa sociedade. Ainda atentos ao que Marc Bloch relata: 
	
> Velho medievalista, confesso não conhecer leitura mais atraente do que um cartulário. É que sei aproximadamente o que lhe perguntar. Uma coletânea de inscrições romanas, em contrapartida, me diz pouco. Se com dificuldade consigo lê-las, não sei solicitá-las (BLOCH, 2002, p.79).

Ou seja, parafraseando o historiador francês: uma coletânea de tweets ou milhões de metadados sobre publicações acadêmicas ou um jornal digitalizado dirão pouco aos historiadores que não conseguirem lê-los de forma adequada, com ferramentas e habilidades coerentes com suas especificidades. Como afirmar Brasil e Nascimento: 

>Quando um registro histórico — seja ele um manuscrito, uma carta, uma edição de jornal, uma foto, um livro etc. — converte-se, por meio de algum processo computacional, em um documento digital, ocorre aí uma mudança que dificilmente poderia ser considerada trivial. Apesar de a informação contida na fonte continuar “sendo a mesma” — no sentido de que a digitalização não alteraria substancialmente o conteúdo do registro histórico —, podemos dizer que a modificação na “materialidade” da fonte histórica nos conduz, inevitavelmente, a uma nova condição em relação ao modo de lidarmos com a informação ali contida. (Brasil e Nascimento, 2020, p. 201)

Sobre a reflexão acerca da utilização das fontes em meios digitais, Helle Jensen (2020) aponta como um dos aspectos a necessidade de entender a política da instituição que organiza e publiciza tais fontes, além de entender a lógica desses processos pois, “A qualidade da pesquisa histórica depende da compreensão dessas lógicas porque elas tem consequências metodológicas.” (Jensen, 2020, p.2. tradução nossa). 

Neste sentido, sabemos que as publicações dos papers da ANPUH passaram por um conjunto de procedimentos metodológicos de avaliação próprios da academia, e que os interesses da publicização de tais conteúdos estão associadas a difundir conhecimento epistêmico de acordo com as recomendações éticas da escrita historiográfica. Porém, gostaríamos de pontuar algumas considerações acerca da estrutura. Parte da metodologia demandou uma análise mais detalhada dos papers devido ao caráter subjetivo da linguagem, assim, fizemos a leitura próxima de 185 pdfs - procedimento que será descrito abaixo -, o que nos fez perceber algumas lacunas em relação à estrutura dos papers, como a ausência de informações sobre autoria, instituição ou formação e, em alguns momentos sentimos dificuldade em relacionar o título com o corpo do texto, bem como identificar do que se tratava a temática geral.

## Parte II- Desenvolvimento da pesquisa

A pesquisa de base que deu origem a essa monografia foi desenvolvida ao longo dos anos de 2020 e 2021 através do projeto PIBIC “Pós-abolição: usos, sentidos e produções acadêmicas 2004-2019”, onde desenvolvi o plano de trabalho "Análise do termo “pós-abolição” em produções acadêmicas (2004-2019)".

Para desenvolvimento da pesquisa, utilizamos uma metodologia híbrida, com técnicas próprias da ciência computacional e práticas de pesquisa historiográfica. Para isso, fizemos formação para utilizar ferramentas digitais específicas como o Zotero e Atlas.ti 7, e de compreensões básicas sobre a linguagem de programação Python. Tivemos momentos de leitura da bibliografia do projeto e reuniões para discussão da mesma no intuito de construir um arcabouço teórico para nortear a análise qualitativa dos dados.

Sobre a formação teórica, após levantamento bibliográfico das temáticas mais pertinentes, dado o caráter do projeto de buscar caracterizar produções historiográficas em meios digitais, sobre Humanidades Digitais, priorizamos leituras que tratassem de possíveis conceituações deste campo, que avaliassem como ferramentas digitais podem ser utilizadas na pesquisa historiográfica, os impactos da tecnologia no ofício do historiador, e da importância de acompanhar e criticar os avanços tecnológicos para a construção do conhecimento histórico. Dessa forma, incidimos em trabalhos que estavam mais voltados para as discussões no âmbito da Sociologia  e da História como "As Humanidades Digitais como uma comunidade de práticas dentro do formalismo académico: dos exemplos internacionais ao caso português",(Daniel Alves); "História Digital: reflexões a partir da Hemeroteca Digital Brasileira e do uso de CAQDAS na reelaboraçõa da pesquisa histórica",(Eric Brasil e Leonardo Nascimento); "Novas fronteiras metodológicas nas ciências sociais", (Leonardo Nascimente e Paulo Alves); "Bit by bit: social research in the digital age",(Matthew Salganik);"Evidências, códigos e classificações: o ofício do historiador e o mundo digital",(Alexandre Fortes e Leonardo Alvim);"Digital history e Storiografia digitale : estudo comparado sobre a escrita da história no tempo presente (2001-2011)",(Anita Lucchesi);"Nunca fomos tão úteis",(Anita Lucchesi et all); e, "HISTÓRIA DIGITAL, SOCIOLOGIA DIGITAL E HUMANIDADES DIGITAIS: Algumas questões metodológicas",(Helyom Telles) . 

Para as leituras sobre o pós-abolição, partimos da abordagem feita por Ana Lugão Rios e Hebe Mattos (2004) no artigo “O pós-abolição como um problema histórico: balanços e perspectivas ”, de que existe uma grande diversidade de elementos a serem explorados para compor os estudos do pós-abolição no Brasil, e que estes elementos ainda estão emergindo na historiografia, possibilitando sua consolidação como um campo autônomo. Assim, preferimos destacar trabalhos que pudessem nortear estes elementos, sobretudo, pela necessidade na definição de parâmetros a serem utilizados na análise das publicações no software de apoio a análise qualitativa de dados. 

As leituras estiveram presentes em todas as etapas da pesquisa pois, além da necessidade de fundamentação teórica própria do formato da monografia, foi necessário como previsto pelas Humanidades Digitais, a adequação das ferramentas para a finalidade específica da pesquisa.

Em seguida, fizemos capacitações para uso do gerenciador bibliográfico Zotero, o qual utilizamos para criar uma biblioteca pública digital de referências bibliográficas, intitulada “História Digital” e para fazer o levantamento bibliográfico. A utilização do Zotero nos ajudou na organização da bibliografia tanto quanto na escrita desta monografia, devido as diversas funcionalidades que possui, como por exemplo, a automatização da inserção das citações escritas no corpo do texto a partir da bibliografia predefinida nele em diretório criado especificamente para o TCC.[^2]

[^2]: Para uma utilização prática e avaliação dos impactos do Zotero na pesquisa histórica, ver LUCCHESI, Anita. *Digital history e Storiografia digitale*: estudo comparado sobre a escrita da história no tempo presente (2001-2011). Mestrado, UFRJ, Rio de Janeiro, 2014. p. 62-64

Dentre essas capacitações, fizemos uma formação online da UDESC sobre Zotero, alguns workshops ministrados pelo professor Eric Brasil, e tivemos acesso a algumas aulas ministradas pelo mesmo na disciplina de Ferramentas Digitais e a pesquisa em humanidades no IHL, Unilab. Após as capacitações, criamos um grupo público no Zotero (o qual tornou-se a página da biblioteca) com um banco de dados constituído de teses, capítulos de livros, artigos, conferências, livros, verbetes de enciclopédia e página da web; organizamos as referências e todas as informações constantes nos metadados seguindo os padrões da ABNT; criamos etiquetas para cada artigo e pastas temáticas de maneira a otimizar a busca pelo público. 

O Zotero é um gerenciador bibliográfico gratuito e de software livre. Entre suas funções básicas está o armazenamento, o gerenciamento de referências, a organização por conjunto de dados de temáticas específicas dispostos em pastas ou *“Coleções”*, e a inclusão de citações em editores de texto por meio de integração. Permite ainda a adição de marcadores que identificam os arquivos que são as etiquetas ou *“tags”*, além da possibilidade de criação de grupos públicos(o que te permite construri bibliotecas públicas) e da sincronização entre diversos computadores através de um servidor.(SILVA; ANDRETTA; RAMOS, 2011, pág. 429). É importante apontar que o Zotero além das funcionalidades citadas, preserva a mesma estrutura de visualização *online* e *offline*, além de permitir fazer fichamentos e buscas mais detalhadas através das etiquetas.(LUCCHESI, 2014, pág.62). Atualmente está na 6ª versão e com diversas outras funcionalidades implementadas. 

A criação da biblioteca pública de referências no Zotero intitulada História Digital foi desenvolvida em conjunto com a discente Ana Carolina de Oliveira Veloso do curso de História, bolsista Pibic/Fapesb projeto “História Digital:  acervo e ferramentas digitais para pesquisa e ensino”, sob a orientação do professor Eric Brasil no âmbito do curso de Licenciatura em História, da UNILAB-campus Malês. 

Para a criação da biblioteca foi necessário construir coleções, que são um conjunto de referências agrupadas por temáticas, definidas nas etiquetas, que são marcadores que sintetizam palavras-chaves ou conceitos. No presente momento a biblioteca conta com mais de 300 itens, organizados em 13 coleções (Tabela 1).

|Nome da coleção                                          |Quantidade de Itens|
|---------------------------------------------------------|-------------------|
|Acervos e Arquivos Digitais                              |30                 |
|Definições de tecnologias                                |4                  | 
|Ensino e Humanidades Digitais                            |9                  | 
|Ferramentas Digitais                                     |48                 | 
|Hemerotecas e Bibliotecas Digitais                       |23                 | 
|Heurística Digital                                       |4                  | 
|História Publica Digital                                 |10                 | 
|Humanidades Digitais                                     |40                 | 
|Memoria                                                  |4                  | 
|Metodologias Digitais                                    |51                 | 
|NLP e NER                                                |24                 |  
|Reflexões Críticas: decolonialidade e interseccionalidade|26                 | 
|Teoria e Epistemologia da História                       |42                 | 


Essas coleções foram definidas pensando nos principais recortes onde se aborda a temática da História Digital e temas interligados. A biblioteca continua em constante atualização, podendo ter referências adicionadas por quem tiver interesse em colaborar com o projeto, mediante avaliação do administrador.  Atualmente, a biblioteca conta com quatorze membros, podendo ser acessada neste [link](https://www.zotero.org/groups/2216280/histria_digital).

Na etapa seguinte, passamos a trabalhar diretamente com a base de dados criada a partir da raspagem dos Anais dos Simpósios Nacionais de História da Anpuh. Diante da necessidade de compreender o funcionamento do *script* para raspagem dos dados nas plataformas, o qual foi criado pelo professor Eric Brasil em parceria com o Laboratório de Humanidades Digitais da UFBA, fizemos workshops de linguagem de programação orientada a objeto, com a linguagem Python. 

Podemos resumir o processo de coleta dos dados da seguinte maneira: dois *scripts* de raspagem de dados referentes aos trabalhos completos publicados nos anais da Anpuh foram criados. Ambos escritos em Python 3.8 [^3]. O primeiro deles, `script-anais-anpuh.py` realizou a raspagem dos trabalhos em PDF de todos os Simpósios Nacionais da Anpuh entre 1963 até 2017, atualmente disponíveis na página oficial da associação. O segundo script, `script-anais-anpuh-2019.py`, é um desdobramento do primeiro para raspar os trabalhos publicados nos Anais do 30º Simpósio Nacional de História, realizado no ano de 2019 em Recife, PE, visto que ainda não estão disponíveis no repositório do site da Anpuh.

[^3]: Python é uma linguagem de programação com uma curva de aprendizagem menor, que te permite trabalhar rapidamente, e integrar diferentes sistemas com maior eficiência. Para saber mais, acesse https://www.python.org/downloads/

Ambos os scripts estão disponíveis no repositório Anais-Anpuh no GitHub do Laboratório de Humanidades Digitais da UFBA e podem ser acessados através desse link: https://github.com/LABHDUFBA/Anais-Anpuh.

A sequência lógica do funcionamento do script para a raspagem foi criar uma pasta para salvar os PDFs, acessar a url dos Anais da ANPUH, criar uma lista de eventos a partir da página principal, acessar as páginas específicas de cada evento e em cada item da lista buscar os papers e criar uma nova lista. Em cada item desta nova lista, encontrar as informações específicas do paper, criar uma nova lista com as informações, verificar se há pdfs disponíveis e se não é repetido e fazer o download do mesmo. Isso ocorre repetidas vezes até que o script percorra todas as páginas de todos os eventos.

Para que o script pudesse integrar as diversas etapas citadas anteriormente, foi necessário utilizar algumas bibliotecas (conjunto de funções e métodos que compõem um módulo para ser utilizado no desenvolvimento de códigos de programação) e módulos (que são um conjunto de instruções específicas descritas em um único arquivo) do Python 3, sendo eles:

- urllib.requests: módulo do Python para acessar urls. Saiba mais.
- os: módulo do Python que permite manipular funções do sistema operacional. Saiba mais.
- bs4: Beautiful Soup é uma biblioteca Python para extrair dados de arquivos HTML e XML.
- re: Regular Expressions é um módulo do Python para operar com expressões regulares.
- pandas: Pandas é uma biblioteca escrita em Python para manipulação e análise de dados.
- wget: Wget é uma biblioteca escrita em Python para realizar downloads. 

Após a coleta dos dados com o programa, temos como resultado um dataset formado por trinta e quatro pastas, do primeiro SNH até o trigésimo (quatro eventos possuem pastas de resumos além dos eventos completos). Essa raspagem resultou em uma base de dados com 15.157 PDFs, que em seguida foram filtrados cronologicamente devido aos objetivos específicos da pesquisa, a partir do 27º SNH no ano de 2013. Como intuito principal está em entende como o termo pós-abolição tem sido tratado nos simpósios da ANPUH,  essa seleção se justifica por esse ter sido o evento de fundação do Grupo de Trabalho Emancipações e Pós-Abolição.

Esse novo dataset filtrado cronologicamente conta com 6.434 arquivos em PDF de trabalhos completos publicados. Lembrando que número de trabalhos submetidos, aprovados e apresentados nos eventos é muito maior.

Em sequência, fizemos uma formação para utilização do programa ATLAS.ti 7 com o professor Eric Brasil e com o LABHDUFBA. O ATLAS.ti (Archive of Technology, Life word ad Language for Text Interpretation) se enquadra a categoria de programas CAQDAS (Computer Assisted Qualitative Data Analysis) para apoio a pesquisa qualitativa de dados através da leitura computadorizada de diversas fontes digitais. É um software de código fechado, com direitos exclusivos, sendo necessário licença para uso. Sua criação partiu de um projeto em 1986, do professor Heiner Legewie, na Universidade Técnica de Berlim, que objetivava construir um arquivo de dados que pudesse auxiliar nas entrevistas de uma pesquisa sobre os sobreviventes de Chernobyl. Em parceria com pesquisadores das áreas de sociologia, linguística e computação foi desenvolvida a primeira versão, que consistia em auxiliar na seleção de fragmentos de entrevistas, categorizá-los e adicionar anotações sobre tais fragmentos para análise sistemática.

Posteriormente, o software foi sendo aprimorado, culminando na diversidade de funcionalidades das versões atuais. Dentre estas funcionalidades, podemos destacar a criação de códigos (codes) que são marcadores - normalmente uma palavra ou frase que sintetiza alguma compreensão teórica -  para um conjunto de trechos selecionados (quotations). Estes códigos podem possuir códigos filhos e uma família de códigos, além de outras relações entre si. Estas redes de relações (network) também são uma funcionalidade passível de utilização para construção de objetos de análise, gerando árvores de códigos. Dispõe ainda de uma função para anotações (memos), sendo possível adicioná-la a qualquer um destes elementos. (BRASIL; NASCIMENTO, 2022).

Após estarmos de posse da base de dados em formato digital, devemos criar um projeto no ATLAS.ti (que em sua versão 7 é intitulado Unidade Hermenêutica) e inseri-la no programa. Fizemos isso com todos os 6.434 PDFs selecionados. Cada item passa a ser denominado de Document ou Primary Document. Destes 6.434 Documents precisávamos selecionar quais continham o termo pós-abolição. Para isso, utilizamos a função Auto-Coding, que consiste em uma seleção automatizada de trechos (quotation ou citação) a partir de um elemento textual pré-definido manualmente. Essa função aceita a aplicação de _regular expressions_, ampliando as possibilidade de busca e precisão nos resultados. Assim, aplicamos o operador `|` (que significa 'ou') combinando um conjunto de expressões: `pós-abolição|pos-abolição|pós-abolicionismo|pós-emancipação|pos-emancipação`. Não foi necessário criar uma combinação para diferenciar caracteres maiúsculos e minúsculos pois o padrão do aplicativo é fazer a leitura do termo sem diferenciá-los, dispondo da função _Case Sensitive_ para isto. Como nesse momento se tratava de uma estratégia para selecionar todos os arquivos que contivessem o termo, preferimos que todo o corpo do PDF fosse selecionado ao invés de parágrafos. Esse procedimento resultou na identificação de 183 PDFs.

Em seguida, elaboramos a árvore de códigos que refletem nossas compreensões teóricas sobre o pós-abolição. A árvore de códigos é a estrutura organizacional dos códigos, a lógica utilizada para expressar os conceitos que estes códigos representam e como eles se relacionam (BRASIL e NASCIMENTO, 2022). É possível com isso analisar a frequência desta relação e a interdependência destes elementos, consequentemente a relação entre os sentidos que eles representam, entre outras análises.

Na árvore, é possível criar diferentes famílias de códigos. As famílias tem como objetivo agrupar códigos que estão vinculados a uma mesma temática. Assim, utilizamos códigos pais, que estão no topo dessa árvore, códigos filhos e, em alguns casos, códigos netos. Ambos são a ramificação de um código pai, e representam parte de uma mesma família, podendo também manter relações com códigos de outras famílias. São eles:

- **TEMÁTICA_GERAL**: É a temática específica da publicação, qual assunto está sendo abordado. Estes são os elementos pelo qual emergiram as discussões sobre o pós-abolição, e representam as diversas agências utilizadas para a discussão do campo. 

- **ANÁLISE_PÓS-ABOLIÇÃO**: Código utilizado para identificar o trecho da publicação que contém o termo e, em qual sentido ele está sendo utilizado. Representa o código central do projeto. Estes códigos foram desenvolvidos a partir de possibilidades de usos percebidos através da leitura da bibliografia e da identificação nos próprios papers. Identificamos os seguintes sentidos:
  
- **ANÁLISE_PÓS-ABOLIÇÃO::TEMA_CENTRAL**: Este código é um marcador para indicar quando a abordagem central do artigo for sobre o pós-abolição, funciona como o código pai dos códigos de análise específica de sentidos do pós-abolição, sendo utilizado juntamente com eles.

- **ANÁLISE_PÓS-ABOLIÇÃO::TEMA_INCIDENTAL**: Funciona da mesma maneira que o anterior, no entanto, quando a abordagem central do artigo NÃO tratar de pós-abolição, mas o termo for utilizado no texto de forma incidental ou tangencial.

- **ANÁLISE_PÓS-ABOLIÇÃO::TEMA_INCIDENTAL_CORPO**: Este código foi criado apenas para identificar quando o termo for utilizado incidentalmente em citações de títulos ou situações afins ao longo do corpo do texto, em oposição ao código que identifica a citação no rodapé ou na bibliografia.	
  
- **ANÁLISE_PÓS-ABOLIÇÃO::NOTA_RODAPÉ**: quando o termo aparece na nota de rodapé através de uma citação atrelada aos sentidos de análise. 
  
- **ANÁLISE_PÓS-ABOLIÇÃO::TEMA_INCIDENTAL_RODAPE_BIBLIOGRAFIA**: Este código foi criado para identificar quando o termo for citado na bibliografia ou notas de rodapés sem estar atrelado a nenhum sentido de análise 

- **ANÁLISE_PÓS-ABOLIÇÃO::ASPECTO_POLÍTICO**: Identifica se há análise ou categorização dos usos políticos do termo.

- **ANÁLISE_PÓS-ABOLIÇÃO::CAMPO_DE-PESQUISA/ESTUDO**: Mostra o pós-abolição como um campo de pesquisa acadêmico.

- **ANÁLISE_PÓS-ABOLIÇÃO::CRÍTICA_DO_TERMO**: Quando é feita uma análise crítica do termo.

- **ANÁLISE_PÓS-ABOLIÇÃO::DEFINIÇÃO_DO_TERMO**: Quando há definição ou explicação do termo.

- **ANÁLISE_PÓS-ABOLIÇÃO::EXTINÇÃO_DO_CATIVEIRO**: Código que identifica o pós-abolição como a mudança jurídica que destitui a propriedade legal sobre o indivíduo negro fazendo um contrapondo escravidão e  liberdade.

- **ANÁLISE_PÓS-ABOLIÇÃO::PERSPECTIVA_COMPARATIVA**: Quando há comparação com outros termos.

- **ANÁLISE_PÓS-ABOLIÇÃO::PERSPECTIVA_TEÓRICA**: Esse código foi criado para os trechos que contém o termo porém não o definem, utilizando-o enquanto um conjunto de elementos.	

- **ELEMENTOS_TEXTUAIS**: Identifica os autores e sua formação, a instituição a qual está vinculado, o evento e o título da publicação. 

- **REC_ESPACIAL** – Identifica à localização geográfica na qual a temática geral da publicação está inserida.

- **REC_TEMPORAL** – Refere-se ao tempo cronológico no qual a temática está situada. Não foi possível criar um padrão através da cronologia histórica, pois, a definição temporal para os períodos por vezes não se enquadrou no tempo percorrido pelas publicações, o que nos levou a construir o recorte por século.

Queremos destacar que os códigos foram desenvolvidos de maneira dinâmica e, embora as leituras bibliográficas tenham nos ajudado a construir o arcabouço inicial da codificação, outros elementos foram emergindo à medida que fomos analisando os papers, assim, para que pudéssemos construir um conjunto de códigos coeso foi necessário que fizéssemos a leitura próxima e a análise de todas as 185 publicações, o que mostra a importância de uma combinação de leitura computadorizada (raspagem, filtragem + auto-coding)  associada a análise qualitativa humana a partir da leitura para compreensão do contexto, dada a  subjetividade da linguagem. Embora julguemos importante a incorporação do Processamento de Linguagem Natural (NLP) à pesquisa qualitativa, método ainda distante da realidade historiográfica brasileira, compreendemos ser um processo complexo que envolve conhecimento e específicos e maior criticidade, os quais ainda não dispomos nesse momento.

Ao finalizar a codificação, geramos arquivos do tipo csv (*Comma-separated value*), formato escolhido devido a portabilidade entre diversos sistemas e plataformas, que consistem em um arquivo com ordenação própria que usa vírgulas como separador (KARSDORP, Folgert; KESTEMONT, Mike; RIDDELL, Allen. Humanities data analysis: case studies with Python. Princeton: Princeton University Press, 2021. p.36). Os quais foram utilizados como um dataset para a base de dados dos gráficos que foram gerados pelo professor Eric Brasil com o pandas, que é uma biblioteca de código aberto, utilizada em IDE’s de linguagem python para análise de dados, onde são convertidos e dispostos em formas tabulares, constituindo um *dataframe* (assemelha-se a uma tabela). Estes gráficos compõem parte dos anexos que ilustram a monografia.

Todos os dados e informações da pesquisa encontram-se no Github. O GitHub é uma plataforma gratuita e de código aberto, de repositório ilimitado, com um *workflow* próprio, que te permite trabalhar de forma colaborativa, gerando transparência tanto na apresentação dos resultados como no processo de desenvolvimento da pesquisa, permite  manter os dados para acesso futuro desde a primeira inserção, com acompanhamento das modificações, além de possuir diversas funcionalidades para gerenciamento de projetos como  as mensagens de *commit* que permitem documentar a pesquisa, o *readme.md* que permite uma visualização (apresentação) inicial da pesquisa e criação de planos de trabalhos específicos que podem ser automatizados conforme as tarefas (*issues*) forem sendo modificadas. Como o GIT é um controlador de versões distribuído, possibilitando trabalhar por branches (ramificações com snapshot de todo o repositório em um dado momento que são armazenados localmente), confere maior agilidade e segurança para o fluxo de trabalho e para o backup de dados, além de permitir a recuperação de qualquer versão. Embora seja uma ferramenta que foi inicialmente desenvolvida para ser utilizada por programadores e demande uma curva de aprendizagem maior, é uma alternativa altamente eficiente para o armazenamento, controle e gerenciamento de projetos das diversas áreas.

Os dados referente ao projeto “Pós-abolição: usos, sentidos e produções acadêmicas 2004-2019”, analisados aqui, podem ser acessados no GitHub na página do projeto PIBIC em: <https://github.com/ericbrasiln/pibic_2020-2021/tree/main/EDITAL_UNILAB> e os gráficos interativos e outros recursos pode ser visto aqui: https://ericbrasiln.github.io/pibic_2020-2021/pos-abolicao/

Optamos por tornar os dados dessa monografia públicos por acreditarmos na importância do desenvolvimento de pesquisas em diálogo com a ciência aberta como um dos caminhos para tornar o desenvolvimento epistêmico menos generalista e autoritário. O acesso aos dados da pesquisa colaboram para diminuir a possibilidade de conclusões históricas generalizadas que apontam mais para as intenções políticas do historiador do que para análise das fontes em si, além de diminuir o privilégio do acesso as mesmas(CARDOSO et al., 2021).

Assim, todo o processo de escrita da monografia foi registrado e comentado utilizando sistema de controle de versões com Git e hospedado no repositório remoto no GitHub, que pode ser acessado aqui: https://github.com/priscilavalverdes/TCC-Pos-abolicao. O histórico com todas as alterações podem ser recuperadas.

Embora entendamos que uma análise detalhada dos dados seja um procedimento que demanda um tempo maior, faremos no capítulo a seguir a apresentação dos dados quantitativos e uma breve análise qualitativa com maior atenção ao uso do termo pós-abolição.
