# Considerações finais {.unnumbered}

Sobre a caracterização das publicações, percebemos maior incidência de autores que eram mestrandos e doutorandos do que mestres, ou doutores. Observamos com isso que o termo tem sido muito usado por acadêmicos em formação: mestrandos e doutorandos, o que pode ser um indicativo de que o termo terá ainda muita produção nos próximos anos. Identificamos 53 instituições de Ensino Superior, mais de 95% delas são públicas. Esses dados, sobretudo no atual governo, que tem tentando devastar o ensino público, principalmente no que tange as disciplinas relacionadas às áreas de Humanidades, é um indicador da importância de financiamento por parte do Estado à políticas de desenvolvimento educacional gratuito para garantir educação de qualidade e possibilitar a manutenção da produção historiográfica nacional.

Como já mencionado, a variedade das temáticas expressa as diversas possibilidades de caminho para estudar o pós-abolição, que embora esteja em ascensão, ainda deixam um campo vasto de estudo em aberto, como nos alertou Hebe Matos e Ana Lugão Rios há quase duas décadas. Percebemos a preferência dos autores por elementos e metodologias suscitadas pela História Social e pela Micro-História, sobretudo quando analisamos o quantitativo de trajetórias.

Na análise do conjunto dos dados, diante de observarmos a diversidade de temáticas e percebermos que a maior parte delas não está preocupada em indicar uma narrativa única, mas de apontar atores e ações dos diversos “brasis” que por muito tempo esteve fora da historiografia nacional, e da baixa incidência de utilização do termo do pós-abolição com um sentido específico, sendo apresentado na maior parte enquanto uma perspectiva teórica ampla, concluímos que os estudos recentes sobre o pós-abolição tendem a indicar um campo de fala das margens, o que é de extrema importância e representa uma consciência crítica em uma sociedade racializada como o Brasil, mas que ainda carece de um debate metodológico mais aprofundado.
