# Introdução {.unnumbered}

Até o início da segunda metade do século XX, parte significativa da historiografia brasileira apontava a então chamada Lei Áurea (Lei n° 3.353 de 13 de maio de 1888) como o principal evento para entender o fim da escravidão e o início de um novo período histórico. Porém, com as demandas dos movimentos sociais negros que emergiram na década de 1960 reivindicando reparações aos danos causados pela escravidão que afetavam (e ainda afetam) os povos africanos e afro-brasileiros no Brasil – o que aponta a abolição como um processo inacabado – surgiu também a necessidade de revisitar a História. 

Até meados da década de 1980, muitas vertentes da historiografia brasileira buscava analisar os processos históricos e as mudanças sociais deles decorrentes a partir de um conjunto de ações que não incluíam as questões raciais (NASCIMENTO,2016). Como afirma Álvaro Nascimento, analisando a história social do trabalho, estas ações tenderam sempre a apontar um protagonismo branco. Como culminância de décadas de lutas e produções intelectuais e homens e mulheres negras e tantos outros brancos e não brancos, nos movimentos sociais, nas associações religiosas e festivas e também nas universidades e escolas, os estudos do Pós-Abolição tem ajudado a consolidar a quebra desse paradigma indicado por Nascimento.

Em primeiro lugar, o pós-abolição, embora caminhe por vias próprias, mantém relação com a história social da escravidão e, se tratando da percepção sobre o negro nos estudos acerca da escravidão, até 1980 existia uma dicotomia na historiografia que associava o escravizado a dois tipos específicos de perfis. De um lado, uma personalidade passiva, que denotava convivência harmoniosa entre escravos e senhores o que inferia uma relativa autoaceitação do próprio escravo em seu papel dentro da sociedade, apresentando a abolição como um projeto de elite. Do outro, o escravo heroico, rebelde, que empreendia levantes e revoltas contra o sistema escravista o que atribuía ao escravo um certo endeusamento, retirando-lhe  em certa medida seu caráter humano e a capacidade de por si mesmo reconstruir sua história (REIS; SILVA, 1989).

O trabalho de João Reis e Eduardo Silva, “Negociação e Conflito”, publicado em 1989, aponta, sem desqualificar a importância das personalidades negras mais populares no processo de abolição, que o fim da escravidão foi o resultado de um conjunto de processos e de ações que se desenrolam no dia a dia por atores que não se engessam em nenhuma das duas categorias, indicando que “Os escravos não foram vítimas nem heróis o tempo todo, se situando na sua maioria e em sua maior parte do tempo numa zona de indefinição entre um e outro pólo.” (REIS; SILVA, 1989, p.7). Essa perspectiva colabora para imprimir nos estudo do pós-abolição perspectivas da micro-história e trajetórias individuas e coletivas.

O segundo aspecto que queremos apontar está relacionado a invisibilidade do negro na transição da Monarquia para a República. Nos estudos sobre o pós-abolição tornou-se imprescindível incluir reflexões sobre as questões raciais na análise histórica. No artigo “Trabalhadores Negros e o Paradigma da Ausência: Contribuições à História Social do Trabalho no Brasil”,  Álvaro Nascimento aponta como as lacunas deixadas pela ausência de identificação de cor invisibilizou o negro nas narrativas, embora ele sempre estivesse presente em todos os setores da sociedade, sendo impossível tratar dela sem incluí-lo. Apesar de seu trabalho buscar majoritariamente tratar sobre a História Social do Trabalho, Nascimento traz importantes reflexões sobre as possibilidades de pesquisa que mostram caminhos para desconstruir a invisibilidade do negro em qualquer área da historiografia.

Ao contrário da passividade apontada por um ou da invisibilidade apontada por outro, os estudos recentes vêm analisando um conjunto de ações, instituições e indivíduos, mostrando que o pós-abolição se apresenta como um campo de conflitos e tensões permanente (GOMES; DOMINGUES, 2011), de embates onde os homens e mulheres negras possuem fala e agência, apesar da violência, racismo e desigualdades no processo histórico.

Para os recém libertos, o dia seguinte à abolição possuía sentidos múltiplos, era o direito à cidadania, o direito à terra, a constituição de família, ou a consolidação legal dessas ações, por vezes experimentadas, mas incertas. Guardava – e ainda guarda – muitas inseguranças da permanência desta recente liberdade, principalmente diante dos boatos e incertezas que marcavam o advento da República (ALBUQUERQUE, 2009). A luta pela garantia destes direitos, agora assegurados pelo sistema jurídico nacional, e as lutas por sua expansão marcam a sociedade brasileira após o 13 de Maio. As experiências do pós-abolição variam tanto quanto os sentidos que se dá a Liberdade. Mas, 134 anos depois, o que é o pós-abolição para a historiografia no Brasil?

Buscando identificar como tem sido tratado o campo na atualidade, fruto do projeto de pesquisa PIBIC “Pós-abolição: usos, sentidos e produções acadêmicas 2004-2019”, com bolsa financiada pela UNILAB, orientado pelo professor Eric Brasil, este monografia objetiva discutir alguns resultados acerca do que tem se produzido nos Simpósios Nacionais de História da Associação Nacional de História (ANPUH) sobre o pós-abolição, aliado às discussões metodológicas próprias das Humanidades Digitais, mais especificamente da  História Digital. 

As Humanidades Digitais vêm se consolidando enquanto um campo de pesquisa, indicando ora ser um conjunto de métodos de pesquisa que aborda usos técnicos e teóricos dos meios digitais em paralelo à metodologias de pesquisas convencionais de cada disciplina, ora caminha para tornar-se um campo autônomo sem a convergência das discussões específicas das disciplinas. Buscamos fundamentar este projeto em conjunto com referenciais teóricos que indiquem a consolidação deste campo enquanto metodologia híbrida, que associa práticas de pesquisas convencionais às diversas discussões sobre os aspectos sócio-político-culturais do ciberespaço (TELLES, 2017). 

Por se tratar de uma monografia com foco historiográfico, nos apropriamos das discussões da História Digital, que se apresenta como uma ramificação das Humanidades Digitais, sendo um conjunto de abordagens heurísticas próprias da historiografia, associada a metodologias digitais. Não precisaremos fazer esforço para observar que diante do crescente uso tecnológico, faz-se necessário um olhar mais atento do historiador para tal uso. O estudo das sociedades humanas em seu tempo tornou-se indissociável da tecnologia digital? Em alguns anos, senão agora, toda História não será digital?

Como apontou Marc Bloch em *Apologia da História ou o Oficio do Historiador*, a história se faz a partir dos vestígios deixados pelo homem (BLOCH, 2002). Hoje encontramos vestígios de uma sociedade cada vez mais informatizada, onde cada um de nós produz rastros digitais cotidianamente, o que leva a uma dataficação da vida social (SOUTHERTON, Clare. Datafication. In: SCHINTLER, Laurie A.; MCNEELY, Connie L. (Orgs.). Encyclopedia of Big Data. Cham: Springer International Publishing, 2020, p. 1–4). Assim, buscamos refletir sobre as possibilidades de levantar novos questionamentos a partir da utilização de ferramentas digitais como parte metodológica da escrita da história, especificamente do Pós-abolição.

Para tanto, utilizaremos um *dataset* composto de 185 *papers* em formato PDF, e o analisaremos com o software de apoio a pesquisa qualitativa *ATLAS.ti 7* buscando compreender de que maneira o pós-abolição tem sido tratado nos Simpósios Nacionais de História da ANPUH.

A monografia está dividida em três capítulos. No primeiro capítulo, situamos o tempo histórico do qual a pesquisa pretende tratar, a fonte utilizada, caracterizamos a ANPUH e refletimos sobre o que é o pós-abolição para a historiografia recente apoiados em autores como Sidney Chaloub, Petrônio Domingues e Flávio Gomes, Eric Brasil, Fernanda Oliveira, Wlamyra Albuquerque, João Reis e Eduardo Silva, Álvaro Nascimento. O segundo capítulo está dividido em duas partes. Na primeira, conceituamos o que entendemos ser a História Digital, discutimos sobre fontes e a utilização de dados digitais na pesquisa historiográfica, usando como referência Helyom Telles, Marc Bloch, Eric Brasil e Leonardo Nascimento, Anita Lucchesi, Mattew Salganik, Helle Jensen e Adam Crymble. No terceiro capítulo, iremos apresentar os dados quantitativos e apontaremos algumas conclusões por acreditarmos ser importante apresentar os dados resultantes mesmo que a partir de uma breve análise qualitativa.
